Feature/inicial
pandateams/locapy-frontend pull request #1
Opened 2019-04-01 20:36 UTC by Lucas11200

2019-04-02 00:09 UTC, lucassiqueira08 requested changes

2019-04-02 00:09 UTC, lucassiqueira08 commented on src/CadastroLocador.js
> +          </div>
acho que deu ruim aqui, será que foi aspas?

2019-04-02 18:03 UTC, Lucas11200 commented on src/CadastroLocador.js
> +          </div>
Mano, acho que não.. O projeto rodou de boa pra mim... Vc tentou rodar?? Acho q esse vermelho é só no git.

2019-04-06 10:33 UTC, lucassiqueira08 approved these changes

2019-04-14 23:28 UTC, tviniciusilva approved these changes

2019-04-15 16:04 UTC, merged