Feature/rotas
pandateams/locapy-frontend pull request #5
Opened 2019-04-19 16:54 UTC by bruno1576

Rotas pronta.

2019-04-22 00:18 UTC, lucassiqueira08 requested changes

2019-04-22 00:18 UTC, lucassiqueira08 commented on src/CadastroLocatario.js
> +    console.log( data.cpf);
console.log sobrando aqui

2019-04-22 00:18 UTC, lucassiqueira08 commented on src/CadastroLocador.js
> +        console.log(errorResponse);
console.log sobrando aqui

2019-04-22 00:18 UTC, lucassiqueira08 commented on src/CadastroLocatario.js
> +        console.log(errorResponse.response.data);
console.log sobrando aqui

2019-04-22 00:18 UTC, lucassiqueira08 commented on src/CadastroLocatario.js
> +    console.log(cepData);
console.log sobrando aqui

2019-04-22 00:18 UTC, lucassiqueira08 commented on src/dist/ViaCep.js
> +    console.log(cepData);
console.log sobrando aqui

2019-04-27 03:23 UTC, lucassiqueira08 approved these changes

2019-04-29 03:05 UTC, laraujox requested changes
O projeto nao esta rodando

2019-05-04 23:20 UTC, laraujox approved these changes

2019-05-04 23:21 UTC, merged